### PR TITLE
Conditionals page

### PR DESCRIPTION
**Pull request by jasonptoups**

### CODE REVIEW

**Comment by superbuggy** [comment]
Alternatively you can replace the single quotes with backticks `.

**Comment by superbuggy** [comment]
Example...

```js
const stringy = `a string with "double quotes" and 'single quotes'. with backticks \`\` you have to escape with backslash`
```

This is awesome btw!

**Comment by jasonptoups** [comment]
Oh thanks! I will make that fix and then resubmit

**Comment by aspittel** [comment]
Looks awesome!

**Pull request merged**
